name: Format

on:
    push:
        paths:
            - "**/*.rs"
            - "**/*.toml"
            - ".github/workflows/format.yml"
        branches:
            - master
    pull_request:
        paths:
            - "**/*.rs"
            - "**/*.toml"
            - ".github/workflows/format.yml"

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: Format
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --all -- --check
