name: Test

on:
    push:
        paths:
            - "**/*.rs"
            - "**/*.toml"
            - ".github/workflows/test.yml"
        branches:
            - master
    pull_request:
        paths:
            - "**/*.rs"
            - "**/*.toml"
            - ".github/workflows/test.yml"

jobs:
    build:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: Test
              uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --release --verbose
